name: nf-core-metaamplicon-dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # TODO nf-core: Add required software dependencies here
  # - fastqc=0.11.8
  # - multiqc=1.6
  - mothur=1.41.0
